### ISSUE TITLE
Get examples up to date for EDR

### ISSUE THREAD

**Issue by keilw** [javaee/security-examples#2]
The examples have not changed much. Although the API that was extracted from Soteria should be stable, not everything here may still work or use every aspect of the API. We should update existing examples to match the EDR 1 state of the JSR.

**Comment by arjantijms** [comment]
Als tests worked until the API was split off, so it fails because that artefact is not published.

For pretty much every feature a test was added right away, although there are always more cases that can be tested or more variants that can be added.

For now the first test to be added I think should be one that specifically tests the `SecurityContext`. 

@rdebusscher had an example / test of how to replace the identity store handler with a custom (app provided) one, which should probably be good to add here.

**Comment by keilw** [comment]
I'm afraid this no longer makes sense. Applying changes for EE4J is the way to go, so closing it because EDR is long over.
